package scalan.sql

import java.lang.reflect.Method
import scalan._
import scalan.sql.parser.SqlAST.{Index, SortDirection, Table}
import scala.reflect.runtime.universe.{WeakTypeTag, weakTypeTag}
import scalan.meta.ScalanAst._

package impl {
// Abs -----------------------------------
trait DatabasesAbs extends Scalan with Databases {
  self: DatabasesDsl with ScalanSql =>

  // single proxy for each type family
  implicit def proxyDatabase[S <: SSchema](p: Rep[Database[S]]): Database[S] = {
    proxyOps[Database[S]](p)(scala.reflect.classTag[Database[S]])
  }

  // familyElem
  class DatabaseElem[S <: SSchema, To <: Database[S]](implicit _eS: Elem[S])
    extends EntityElem[To] {
    def eS = _eS
    lazy val parent: Option[Elem[_]] = None
    lazy val typeArgs = TypeArgs("S" -> eS)
    override def isEntityType = true
    override lazy val tag = {
      implicit val tagS = eS.tag
      weakTypeTag[Database[S]].asInstanceOf[WeakTypeTag[To]]
    }
    override def convert(x: Rep[Def[_]]) = {
      implicit val eTo: Elem[To] = this
      val conv = fun {x: Rep[Database[S]] => convertDatabase(x) }
      tryConvert(element[Database[S]], this, x, conv)
    }

    def convertDatabase(x: Rep[Database[S]]): Rep[To] = {
      x.selfType1 match {
        case _: DatabaseElem[_, _] => x.asRep[To]
        case e => !!!(s"Expected $x to have DatabaseElem[_, _], but got $e", x)
      }
    }

    override def getDefaultRep: Rep[To] = ???
  }

  implicit def databaseElement[S <: SSchema](implicit eS: Elem[S]): Elem[Database[S]] =
    cachedElem[DatabaseElem[S, Database[S]]](eS)

  implicit case object DatabaseCompanionElem extends CompanionElem[DatabaseCompanionAbs] {
    lazy val tag = weakTypeTag[DatabaseCompanionAbs]
    protected def getDefaultRep = Database
  }

  abstract class DatabaseCompanionAbs extends CompanionDef[DatabaseCompanionAbs] {
    def selfType = DatabaseCompanionElem
    override def toString = "Database"
  }
  def Database: Rep[DatabaseCompanionAbs]
  implicit def proxyDatabaseCompanionAbs(p: Rep[DatabaseCompanionAbs]): DatabaseCompanionAbs =
    proxyOps[DatabaseCompanionAbs](p)

  abstract class AbsDatabaseImpl[S <: SSchema]
      (connectionString: Rep[String])(implicit eS: Elem[S])
    extends DatabaseImpl[S](connectionString) with Def[DatabaseImpl[S]] {
    lazy val selfType = element[DatabaseImpl[S]]
  }
  // elem for concrete class
  class DatabaseImplElem[S <: SSchema](val iso: Iso[DatabaseImplData[S], DatabaseImpl[S]])(implicit override val eS: Elem[S])
    extends DatabaseElem[S, DatabaseImpl[S]]
    with ConcreteElem[DatabaseImplData[S], DatabaseImpl[S]] {
    override lazy val parent: Option[Elem[_]] = Some(databaseElement(element[S]))
    override lazy val typeArgs = TypeArgs("S" -> eS)

    override def convertDatabase(x: Rep[Database[S]]) = // Converter is not generated by meta
!!!("Cannot convert from Database to DatabaseImpl: missing fields List(connectionString)")
    override def getDefaultRep = DatabaseImpl("")
    override lazy val tag = {
      implicit val tagS = eS.tag
      weakTypeTag[DatabaseImpl[S]]
    }
  }

  // state representation type
  type DatabaseImplData[S <: SSchema] = String

  // 3) Iso for concrete class
  class DatabaseImplIso[S <: SSchema](implicit eS: Elem[S])
    extends EntityIso[DatabaseImplData[S], DatabaseImpl[S]] with Def[DatabaseImplIso[S]] {
    override def from(p: Rep[DatabaseImpl[S]]) =
      p.connectionString
    override def to(p: Rep[String]) = {
      val connectionString = p
      DatabaseImpl(connectionString)
    }
    lazy val eFrom = element[String]
    lazy val eTo = new DatabaseImplElem[S](self)
    lazy val selfType = new DatabaseImplIsoElem[S](eS)
    def productArity = 1
    def productElement(n: Int) = eS
  }
  case class DatabaseImplIsoElem[S <: SSchema](eS: Elem[S]) extends Elem[DatabaseImplIso[S]] {
    def isEntityType = true
    def getDefaultRep = reifyObject(new DatabaseImplIso[S]()(eS))
    lazy val tag = {
      implicit val tagS = eS.tag
      weakTypeTag[DatabaseImplIso[S]]
    }
    lazy val typeArgs = TypeArgs("S" -> eS)
  }
  // 4) constructor and deconstructor
  class DatabaseImplCompanionAbs extends CompanionDef[DatabaseImplCompanionAbs] {
    def selfType = DatabaseImplCompanionElem
    override def toString = "DatabaseImpl"

    @scalan.OverloadId("fromFields")
    def apply[S <: SSchema](connectionString: Rep[String])(implicit eS: Elem[S]): Rep[DatabaseImpl[S]] =
      mkDatabaseImpl(connectionString)

    def unapply[S <: SSchema](p: Rep[Database[S]]) = unmkDatabaseImpl(p)
  }
  lazy val DatabaseImplRep: Rep[DatabaseImplCompanionAbs] = new DatabaseImplCompanionAbs
  lazy val DatabaseImpl: DatabaseImplCompanionAbs = proxyDatabaseImplCompanion(DatabaseImplRep)
  implicit def proxyDatabaseImplCompanion(p: Rep[DatabaseImplCompanionAbs]): DatabaseImplCompanionAbs = {
    proxyOps[DatabaseImplCompanionAbs](p)
  }

  implicit case object DatabaseImplCompanionElem extends CompanionElem[DatabaseImplCompanionAbs] {
    lazy val tag = weakTypeTag[DatabaseImplCompanionAbs]
    protected def getDefaultRep = DatabaseImpl
  }

  implicit def proxyDatabaseImpl[S <: SSchema](p: Rep[DatabaseImpl[S]]): DatabaseImpl[S] =
    proxyOps[DatabaseImpl[S]](p)

  implicit class ExtendedDatabaseImpl[S <: SSchema](p: Rep[DatabaseImpl[S]])(implicit eS: Elem[S]) {
    def toData: Rep[DatabaseImplData[S]] = isoDatabaseImpl(eS).from(p)
  }

  // 5) implicit resolution of Iso
  implicit def isoDatabaseImpl[S <: SSchema](implicit eS: Elem[S]): Iso[DatabaseImplData[S], DatabaseImpl[S]] =
    reifyObject(new DatabaseImplIso[S]()(eS))

  // 6) smart constructor and deconstructor
  def mkDatabaseImpl[S <: SSchema](connectionString: Rep[String])(implicit eS: Elem[S]): Rep[DatabaseImpl[S]]
  def unmkDatabaseImpl[S <: SSchema](p: Rep[Database[S]]): Option[(Rep[String])]

  registerModule(Databases_Module)
}

// Std -----------------------------------
trait DatabasesStd extends ScalanStd with DatabasesDsl {
  self: DatabasesDsl with ScalanSqlStd =>

  lazy val Database: Rep[DatabaseCompanionAbs] = new DatabaseCompanionAbs {
  }

  case class StdDatabaseImpl[S <: SSchema]
      (override val connectionString: Rep[String])(implicit eS: Elem[S])
    extends AbsDatabaseImpl[S](connectionString) {
  }

  def mkDatabaseImpl[S <: SSchema]
    (connectionString: Rep[String])(implicit eS: Elem[S]): Rep[DatabaseImpl[S]] =
    new StdDatabaseImpl[S](connectionString)
  def unmkDatabaseImpl[S <: SSchema](p: Rep[Database[S]]) = p match {
    case p: DatabaseImpl[S] @unchecked =>
      Some((p.connectionString))
    case _ => None
  }
}

// Exp -----------------------------------
trait DatabasesExp extends ScalanExp with DatabasesDsl {
  self: DatabasesDsl with ScalanSqlExp =>

  lazy val Database: Rep[DatabaseCompanionAbs] = new DatabaseCompanionAbs {
  }

  case class ExpDatabaseImpl[S <: SSchema]
      (override val connectionString: Rep[String])(implicit eS: Elem[S])
    extends AbsDatabaseImpl[S](connectionString)

  object DatabaseImplMethods {
  }

  def mkDatabaseImpl[S <: SSchema]
    (connectionString: Rep[String])(implicit eS: Elem[S]): Rep[DatabaseImpl[S]] =
    new ExpDatabaseImpl[S](connectionString)
  def unmkDatabaseImpl[S <: SSchema](p: Rep[Database[S]]) = p.elem.asInstanceOf[Elem[_]] match {
    case _: DatabaseImplElem[S] @unchecked =>
      Some((p.asRep[DatabaseImpl[S]].connectionString))
    case _ =>
      None
  }

  object DatabaseMethods {
  }
}

object Databases_Module extends scalan.ModuleInfo {
  val dump = "H4sIAAAAAAAAALVWTYhbRRyfJJvNJ3VdXalgcY2pih9JdZEKQcrapGJJs2FfayUWZfLeJPvqvHmzbybLi4cKHnpQTyIeBA8FxUsRxJtCEaogIkJ79eypVkoP9qT4n3mfkU3XPZjDMG9m8v/4/X7ze+/yTZQXHnpMmJhi1nCIxA1Dz9eFrBsdJm05PeVaE0raZHTtqe/c8rsf9LJoaYAWt7BoCzpApWDS8Xk8N6TVRSXMTCKk6wmJHunqDE3TpZSY0nZZ03acicRDSppdW8hWFy0MXWu6jS6gTBctmS4zPSKJcZxiIYgI14tEVWTHzyX9PN3gSQ7WVF00U12c9rAtoXzIsRSc3yTcmDKXTR2JDoSlbXBVFpypEJ9DD684nOo0uS4q2A53PRllLUCGLdeKHhcYhgW03D2Pd3ATso6bhvRsNlbBODbfwmPSgyPq+AL0IAgdnZ5yEgavCGnN5PM5QghYeU4X1kgwa8SYNRRmdYN4Nqb221ht9j3Xn6Lgl8kh5HMI8fQeIaIIpMOs+nvnzNfvGBUnq/7sq1IKuqBFCPTwHIVoegDbHzc/FLdfvnQ0i8oDVLbF+lBID5syLYMQrgpmzJW65hhB7I2Bwdo8BnWWdTjzL5mUTNfhmEGkEMsqEEVt05bqsFqrhvTMwb4gOYmOZnyeiftdndOv1tJxTGn/xoPPHP6981oWZWdTlCCkAZfBi4JKVGxjgByHMl7U4z0SZQyNsRpKfjIW7pI+BuLxG39YPxxB57IxfGG2/8YYhFh+4ZNvDpP+l1lUHGiBn6B4rLlT+LSJMAeo6O4QL1gv7GCqZrvyV7DICE+oDFFNw5EDOCRanXs3OVFYtbTmM1H7lUC2PZeR+ol+/U/jp48uK1V6qBrsBJf1b/voX78eGEktWKlNgwUyD+5fBHQO7nuMy6PzmOWk79kOuMsOef7qt2duXenlNbnLYXOvYjohQeCwt6RPlT5bq0m0mByY4VQNh3QNKykRHMxETet9iEGMqOiFDiXOnoKRqBqJSxlIkka1emh+qyCABza799Obx65kUf4kyo+AW9FF+aE7YVZ0mwBQSXz5UrSWmeUWbg/2sBNJL/CeVWVd5YAmw3XIvbXb9huX3pdaqRl/1ic3hueBsJZu5qGozYJhmFvEwXGzhV1b31Ppke9/dfHiyq3P3rxPe1NxaEsH8/qRfThTZCT/o/OgWaZzUPbsyv48pJSy75UERy2PtCGl9aLGZ2MO1dPaPhlRYysJuQbcNOZw0yYmxR6xlGiJA2/lAPW1j4+dPXnw7BktlqqlDwU7sYfs/g1xCvOWfuM9cZc3HhyqdxwOXzQwWfv+xevv/PzF59o80o2VYqRlqGPWENs0bqk2pyUjJBiou3Dn096Tv3z9m/aPspIKOBmLvx/SvjFLZ3yZ1VdUQiHslIJMxjZNwQ4uoWSVIqunhs1/ADX0TovXCQAA"
}
}

